apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  # creationTimestamp: "2022-10-20T10:20:14Z"
  generation: 1
  labels:
    app: rest-api
  name: rest-api
  namespace: default
  resourceVersion: "230186"
  uid: b9b090c2-00f1-4c84-a1f8-802fd537eaf5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rest-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rest-api
    spec:
      containers:
      - image: scottyfullstack/basic-rest-api:v01
        imagePullPolicy: IfNotPresent
        name: basic-rest-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-10-20T10:20:46Z"
    lastUpdateTime: "2022-10-20T10:20:46Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-10-20T10:20:14Z"
    lastUpdateTime: "2022-10-20T10:20:46Z"
    message: ReplicaSet "rest-api-dfb9cf5db" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
